# Generated by Django 4.1.4 on 2023-01-31 03:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cam_main', '0003_rename_phonenumber_contact_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Custamer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custamer_name', models.CharField(max_length=150)),
                ('reviwe', models.CharField(max_length=200)),
                ('img', models.ImageField(null=True, upload_to='Custamer_imgs/')),
                ('alt_text', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Prudect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=150)),
                ('details', models.CharField(max_length=200)),
                ('img', models.ImageField(null=True, upload_to='Prudect_imgs/')),
                ('alt_text', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('custamer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cam_main.custamer')),
                ('prudect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cam_main.prudect')),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(max_length=200)),
                ('instagram', models.CharField(max_length=200)),
                ('twiter', models.CharField(max_length=200)),
                ('whatsapp', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='gallery',
            old_name='detail',
            new_name='text_alt',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='title',
        ),
        migrations.DeleteModel(
            name='GalleryImage',
        ),
    ]
