# Generated by Django 4.1.4 on 2023-01-31 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cam_main', '0005_prudect_price_delete_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custamer',
            name='alt_text',
        ),
    ]
